services:
  wms-demo-stock-control:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wms-demo-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped

networks:
  wms-demo-stock-control-default:
    driver: bridge

#  docker build -t agungkusaeri/wms-demo-fst:v2.0.1 --build-arg NEXT_PUBLIC_API_BASE_URL=http://192.168.245.156:3210/api --build-arg NEXT_PUBLIC_SOCKET_BASE_URL=ws://192.168.245.156:3001 .
# docker push agungkusaeri/wms-demo-fst:v2.0.1

# docker build -t agungkusaeri/wms-demo-fst:v2.0.1-2 --build-arg NEXT_PUBLIC_API_BASE_URL=http://192.168.205.170:3210/api --build-arg NEXT_PUBLIC_SOCKET_BASE_URL=ws://192.168.205.170:3001 .
# docker push agungkusaeri/wms-demo-fst:v2.0.1-2


# =============================================================================================

# docker build -t agungkusaeri/wms-demo-fst:staging.nginx --build-arg NEXT_PUBLIC_API_BASE_URL=http://localhost/v1 --build-arg NEXT_PUBLIC_SOCKET_BASE_URL=ws://localhost .
# docker push agungkusaeri/wms-demo-fst:staging.nginx

#  docker build -t agungkusaeri/wms-demo-fst:dev --build-arg NEXT_PUBLIC_API_BASE_URL=http://localhost:3210/api --build-arg NEXT_PUBLIC_SOCKET_BASE_URL=ws://localhost:3001 .
# docker push agungkusaeri/wms-demo-fst:dev

#  docker build -t agungkusaeri/wms-demo-fst:dev.1 --build-arg NEXT_PUBLIC_API_BASE_URL=http://192.168.245.242:3210/api --build-arg NEXT_PUBLIC_SOCKET_BASE_URL=ws://192.168.245.242:3001 .
# docker push agungkusaeri/wms-demo-fst:dev.1
